default_language_version:
  python: python3

repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: ['--py38-plus']
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
    exclude: setup.cfg
  - id: end-of-file-fixer
  - id: debug-statements
- repo: https://github.com/pycqa/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: ['--config=setup.cfg']
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ['--settings-file=pyproject.toml']
- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    args: ['--config=setup.cfg']
- repo: https://github.com/keewis/blackdoc
  rev: v0.3.8
  hooks:
  - id: blackdoc
    additional_dependencies:
    - 'black==23.1.0'
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes

ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks
    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ''
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
  autoupdate_schedule: monthly
  skip: [ ]
  submodules: false
